config/routes.rb
Rails.application.routes.draw do

  get 'shop_pages/index'

  get 'shop_pages/boats'

  get 'shop_pages/shops'

  get 'photo/show'

  get 'photo/destroy'

  resources :property_types
  post "/copy_property_values", to: "property_types#copy_property_values" #для копирования значений свойств с одного типа лодки или продукта на другой
  
  #products
  resources :products
  get "/manage_products", to: "products#manage_index", as: :manage_products
  #product_types
  resources :product_types
  get "/manage_product_types", to: "product_types#manage_index", as: :manage_product_types
  #boat_type_modifications
  resources :boat_type_modifications, only: [:edit, :update]
  #user_requests
  resources :user_requests
  get "my_boats", to: "user_requests#my_requests", as: :my_boats #мои лодки 
  #shops
  resources :shops
  get "/manage_shops/:id", to: "shops#manage_show", as: :manage_shop                #страница управления магазином
  get "/manage_shops", to: "shops#manage_index", as: :manage_shops                  #управление магазинами
  get "/change_shop_status/:id", to: "shops#change_status", as: :change_shop_status #изменение статуса
  get "/manage_shops/:id/boats_for_sale", to: "shops#boats_for_sale", as: :manage_bfs_in_shop #управление лодками в магазине
  get "/manage_shops/:id/product_types/:product_type_id", to: "shops#manage_shop_products", as: :manage_shop_products #управление товарами магазине
  get "/shops/:id/product_types/:product_type_id", to: "shops#shop_products"
  resources :shop_products, only: [:update, :destroy, :create]
  get "/shops/:shop_id/products/:product_id", to: "shop_products#show", as: :in_shop_product
  
  #shop_products
  


  #end
  #locations
  get "/locations/regions/:country_id", to: "locations#regions"
  get "/locations/cities/:region_id", to: "locations#cities"
  get "/add_country", to: "locations#add_country"
  post "/add_country", to: "locations#add_country"
  #end
  #boat_for_sales
  resources :boat_for_sales
  post "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/manage_boat_for_sale", to: "boat_for_sales#manage_index", as: :manage_boat_for_sales
  get "/boat_for_sales/:id/switch_favorites", to: "boat_for_sales#switch_favorites"
  get "/favorites", to: "boat_for_sales#favorites"
  get "/boat_for_sales/:id/buy", to: "boat_for_sales#buy", as: :buy_bfs
  #end
  #boat_option_types
  resources :boat_option_types, only: [:index, :show, :update]
  #end
  #photos
  resources :photos, only: [:show, :destroy]
  post '/upload_photo/:entity/:entity_id', to: 'photos#upload'
  get "/entity_photos/:entity/:entity_id", to: 'photos#entity_photos'
  put "/entity_photos/:id", to: 'photos#update_entity_photo'
  delete "/entity_photos/:id", to: "photos#destroy_entity_photo" #удаляем ссылки на фотографию от boat_type или product (удаление фотографии)
  
  #end
  get "/test_page", to: "pages#test_page"
  get "/about", to: "pages#about", as: :about
  get "/boats/:id", to: "pages#boat", as: :tm_site_boat
  
  resources :boat_series, only: [:index, :create, :update, :destroy, :show]
  resources :trademarks, only: [:index, :create, :update, :destroy, :show]
  root to: 'pages#index'
  
  
  get "/check_user", to: "users#check", as: :check_user
  get "/cabinet", to: "sessions#current_user_page", as: :my
  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup
  
  #get "/boat_types_import", to: "pages#boat_type_import"
  
  
  resources :sessions, only: [:new, :create]
  
  resources :boat_parameter_values, only: [:update]
  get "/boat_parameter_values/:id/:boat_type_id", to: "boat_parameter_values#switch_bind", as: :switch_bind_parameter_value #привязка-отвязка атрибутов от лодки
  resources :boat_parameter_types, only: [:new, :create, :destroy, :edit, :update, :index]
  post "/reorder_boat_parameter_types", to: "boat_parameter_types#update_numbers"
  
  resources :boat_types, only: [:create, :edit, :update, :destroy, :show]
  post '/boat_types/:id/add_configurator_entity', to: "boat_types#add_configurator_entity"  
  get "/manage_boat_types", to: "boat_types#manage_index", as: :manage_boat_types
  get '/boat_types/:id/photos', to: "boat_types#photos", as: :boat_type_photos
  get '/boat_types/:id/videos', to: 'boat_types#videos', as: :boat_type_videos
  get '/boat_types/:id/photos/:photo_id', to: "boat_types#photo", as: :boat_photo
  get '/boat_types/:id/property_values', to: 'boat_types#property_values'
  get '/boat_types/:id/modifications/:modification_id', to: 'boat_types#modification_show', as: :modification
  put '/boat_types/:id/property_values', to: 'boat_types#update_property_values'
  post '/boat_types/:id/modifications', to: 'boat_types#create_modification'
  get '/boat_types/:id/modifications', to: 'boat_types#modifications', as: :boat_type_modifications
  get '/get_boat_types_list', to: 'boat_types#get_boat_types_list'
  post "/copy_photos", to: "boat_types#copy_photos"
  get '/boat_types/:id/options', to: "boat_types#options", as: :boat_type_options
  resources :users
  
  resources :boat_property_types, only: [:index, :create] 
  
  #Realcraft Part--------------------------------------------------------------------------------------
  #get 'about', to: 'realcraft#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "realcraft_pages#dealers", as: :realcraft_dealers
  get 'realcraft190', to: 'realcraft_pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'realcraft_pages#realcraft_200', as: :realcraft_200
  get "wait", to: 'realcraft_pages#please_wait', as: :realcraft_wait
  get "about_realcraft", to: 'realcraft_pages#about', as: :realcraft_about
  post "send_boat_request", to: 'realcraft_pages#send_boat_request', as: :realcraft_send_boat_request
  post "send_dealer_request", to: 'realcraft_pages#send_dealer_request', as: :realcraft_send_dealer_request
  
  
  #videos Part
  resources :videos, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :manager, class_name: "User"
  belongs_to :city
  has_many :boat_for_sales, dependent: :destroy
  has_many :shop_products, dependent: :delete_all
  
  
  def products(product_type_id=nil)
   if product_type_id.nil? 
     shop_products.joins(:product).order("products.name ASC")
   else
     shop_products.joins(:product).where("products.product_type_id = #{product_type_id}").order("products.name ASC")
   end
  end
 
  
  def all_products
    Product.where(id: shop_products.pluck(:product_id))
  end
  
  def region_location
    %{#{city.region.name}, #{city.name}}
  end
  
  def full_location
    %{#{city.country.name}\n #{city.region.name} \n #{city.name} \n #{street}}
  end
  
  def name_with_location
    %(#{name} (#{city.region.name}, #{city.name}))
  end
  
  def self.opened #открытые
    where(is_active: true, is_opened: true)
  end
  
  def self.closed #закрытые
    where(is_active: true, is_opened: false)
  end
  
  def self.recent #недавно добавленные
    where(is_active: false, is_opened: true)
  end
  
  def self.disabled #заблокированные магазины
    where(is_active: false, is_opened: false)
  end
  #проверяет закрыт ли магазин
  def is_opened? 
    is_active && is_opened
  end
  
  def is_closed?
    is_active && !is_opened
  end
  
  def is_recent?
    !is_active && is_opened
  end
  
  def is_disabled? #проверяем заблокирован ли магазин
    !is_opened? && !is_closed?
  end
  
  def available_product_types
    ProductType.where(id: shop_products.joins(:product).select("products.product_type_id AS product_type_id").pluck(:product_type_id)).select(:id, :name, :number_on_boat).distinct
  end
  
  def hash_view
    {id: id, name: name, location: full_location, product_types: available_product_types}
  end
  
  def set_enable_status(status = true) #управляет статусами доступности менеджеру
    self.update_attributes(is_opened: status, is_active: status)
  end
  
  def set_open_status(status = true)
    return false if !is_opened? and !is_recent? and !is_closed?
    return self.update_attribute(:is_opened, status)
  end
  

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :check_grants
  before_action :set_shop, only: [
                                  :change_status, 
                                  :manage_show, 
                                  :show, 
                                  :boats_for_sale, 
                                  :manage_shop_products, 
                                  :shop_products,
                                  :add_product_to_shop, 
                                  :delete_product_from_shop
                                ]
  before_action :set_product_types, only: [:boats_for_sale, :manage_shop_products]
  
  def change_status #возможные статусы #to_open to_close to_disable
    #возможные статусы #to_enable to_open to_close to_disable
    #to_enable разрешено делать только производителям
    #to_disable разрешается делать только производителям
    #to_remove разрешается делать только производителям
    #to_open разрешено делать менеджерам и производителям
    #to_close разрешено делать менеджерам и производителям
    redirect_to "/404" if !could_modify_shop?
    to_status = params[:to_status]
    message = "Не удалось обновить статус магазина"
    if to_status == "to_enable" or to_status == "to_disable" and could_enable_or_disable_shop?
      if @shop.set_enable_status(to_status == "to_enable")
        message = to_status == "to_enable" ? "Магазин успешно активирован" : "Магазин успешно заблокирован"
      end
    elsif to_status == "to_open" or to_status == "to_close"
      if @shop.set_open_status(to_status == "to_open")
        message = to_status == "to_open" ? "Магазин успешно открыт" : "Магазин успешно закрыт"
      end
    elsif to_status == "to_remove" and could_destroy_shop?
      if @shop.destroy
        message = "Магазин успешно удалён из системы"
      end
    end
    render js: "alert('#{message}');Turbolinks.visit(window.location);"
  end
  
  def manage_index
    @title = @header = "Управление магазинами"
    @opened_shops = Shop.opened
    @closed_shops = Shop.closed
    @new_shops = Shop.recent
    @disabled_shops = Shop.disabled
  end
  
  def index
  end
  
  def show
    @boat_for_sales = BoatForSale.manage_collection(@shop.boat_for_sales.ids)
  end
  
  def boats_for_sale
    @boat_for_sales = BoatForSale.filtered_collection(@shop.boat_for_sales.ids)
  end
  
  def shop_products
    @product_type = ProductType.find(params[:product_type_id])
    @products = @shop.products(@product_type.id).to_a.map {|s_product| {id: s_product.id, name: s_product.product.full_name, amount: s_product.amount, properties: s_product.product.prop_vals_for_shop, photos: s_product.product.photos.map{|ph| ph.hash_view}}}
    render json: @products 
  end
  
  def manage_shop_products
    @product_type = ProductType.find(params[:product_type_id])
    @products = @shop.products(@product_type.id)
    @shop_product = ShopProduct.new
  end
    
  def manage_show
    redirect_to manage_bfs_in_shop_path(@shop)
  end
  
  def create
    @shop = Shop.new(shop_params)
    respond_to do |format|
      if @shop.save
        format.js {render js: "Turbolinks.visit(window.location.href);" }  
      else
        
      end
    end

  end
  
  private
  
  def set_product_types
    @product_types = ProductType.not_draft
  end
  
  def set_shop
    @shop = Shop.find(params[:id])
    @title = @header = @shop.name
  end
  def check_grants
    return if !signed_in? and self.action_name == "shop_products"
    redirect_to "/404" if !could_manage_all_shops?
  end
  
  def shop_product_params
    params.require(:shop_product).permit(:product_id, :amount)
  end
  
  def shop_params
    params.require(:shop).permit(:manager_id, :city_id, :street, :name, :phone_number_2, :phone_number_1)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(shop, html: {remote: shop.new_record?}) do |f| %>
    <div class = "row">
        <div class = "small-12 medium-4 end columns tb-pad-xs">
            <% if is_producer? %>
                <%= f.label :manager_id, "Управляющий"%>
                <%= f.collection_select :manager_id, User.managers, :id, :full_name %>
            <% else %>   
                <%= f.hidden_field :manager_id, value: shop.new_record? ? current_user.id : shop.user_id  %>
            <% end %>
        </div>
    </div>
    <div class = "row">
        <div class = "small-12 medium-4 end columns tb-pad-xs">
            <%= f.label :name, "Название" %>
            <%= f.text_field :name, required: "", placeholder: "Название магазина" %>
        </div>
    </div>
    <div class = "row">
        <div class = "small-12 medium-4 end columns tb-pad-xs">
            <%= f.label :phone_number_1, "Контактный номер" %>
            <%= f.text_field :phone_number_1, placeholder: "+7(999)-999-99-99"  %>
        </div>
    </div>
    <div class = "row">
        <div class = "small-12 medium-4 end columns tb-pad-xs">
            <%= f.label :phone_number_2, "Дополнительный номер (не обязательно)" %>
            <%= f.text_field :phone_number_2, placeholder: "+7(999)-999-99-99"  %>
        </div>
    </div>
    <div id = "location-field">
        <div class = "row">
            <div class = "small-12 medium-4 end columns tb-pad-xs">
                <%= label :locations, :country, "Страна" %>
                <%= collection_select :locations, :country, Country.all, :id, :name, {}, {id: "countries"} %>
            </div>
        </div>
        <div class = "row">
            <div class = "small-12  medium-4 end columns tb-pad-xs">
                <label for = "regions">Регион</label>
                <select id = "regions">
                </select>
            </div>
        </div>
        <div class = "row">
            <div class = "small-12  medium-4 end columns tb-pad-xs">
                <%= f.label :city_id, "Населённый пункт" %>
                <%= f.collection_select :city_id, [], nil, nil, {}, {id: "cities"} %>
            </div>
        </div>
        <div class = "row">
            <div class = "small-12 medium-4 end columns tb-pad-xs">
                <%= f.label :street, "Адрес" %>
                <%= f.text_field :street, placeholder: "Улица, дом"  %>
            </div>
        </div>
    </div>
    <div class = "row">
        <div class = "small-12 medium-4 end columns">
            <%= f.submit "Добавить", class: "button success" %>
        </div>
    </div>
<%end%>

app/views/shops/_manage_shop_menu.html.erb
<div class = 'light-gray-bg  tb-pad-xs'>
    <div class = "row">
        <div class = "small-12 columns tb-pad-xs">
            <ul class = 'menu' data-tabs>
                <li class = '<%= controller.action_name == "boats_for_sale" ? "active" : "" %>'>
                    <%= link_to "Лодки", manage_bfs_in_shop_path(@shop) %>
                </li>
                <% @product_types.each do |a| %>
                    <li class = '<%= a == @product_type ? "active" : "" %>'>
                        <%= link_to a.plural_name, manage_shop_products_path(id: @shop.id, product_type_id: a.id) %>
                    </li>
                <%end%>
            </ul>
        </div>
    </div>
</div>

app/views/shops/_shop_product_form.html.erb
<%= form_for(:shop_product, url: add_product_to_shop_path(@shop), html: {remote: true}) do |f| %>
    <div class = "row">
        <div class = "small-12 medium-4 columns tb-pad-xs">
            <%= f.label :name, @product_type.name %>
            <%= f.collection_select :product_id, @product_type.products.order("name ASC"), :id, :full_name %>
        </div>
        <div class = "small-12 medium-4 columns tb-pad-xs">
            <%= f.label :amount, "Цена, руб." %>
            <%= f.number_field :amount, placeholder: "Цена в рублях" %>
        </div>
        <div class = "small-12 medium-4 columns tb-pad-xs">
            <%= f.submit "Добавить", class: "button success" %>
        </div>
    </div>
<%end%>

app/views/shops/_shops_table.html.erb
<table>
  <thead>
    <tr>
      <th>Название</th>
      <th>Администратор</th>
      <th>Контактный номер</th>
      <th>Местоположение</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.manager.full_name %></td>
        <td><%= shop.phone_number_1 %></td>
        <td><span data-tooltip aria-haspopup="true" class="has-tip top" data-disable-hover="false" tabindex="2" title="<%= shop.full_location %>"><%= shop.city.name %></span></td>
        <td><%= link_to "<i class = 'fi-arrow-right'></i>".html_safe, manage_shop_path(shop) %></td>
        <td><%= link_to "<i class = 'fi-pencil'></i>".html_safe, edit_shop_path(shop) %></td>
        <td> 
            <%= link_to "<i class = 'fi-check'></i>".html_safe, change_shop_status_path(id: shop, to_status: "to_enable"), remote: true, "data-turbolinks" => false, title: "Активировать" if shop.is_recent? || shop.is_disabled?  %>
            <%= link_to "<i class = 'fi-prohibited'></i>".html_safe, change_shop_status_path(id: shop, to_status: "to_close"), remote: true, "data-turbolinks" => false, title: "Закрыть"  if shop.is_opened? %>
            <%= link_to "<i class = 'fi-check'></i>".html_safe, change_shop_status_path(id: shop, to_status: "to_open"), remote: true, "data-turbolinks" => false, title: "Открыть" if shop.is_closed? %>
        </td>
        <td>
            <%= link_to "<i class = 'fi-x'></i>".html_safe, change_shop_status_path(id: shop, to_status: "to_disable"), remote: true, "data-turbolinks" => false, title: "Заблокировать"   if shop.is_opened? || shop.is_closed? %>
        </td>
        <td>
                        <%= link_to "<i class = 'fi-trash'></i>".html_safe, change_shop_status_path(id: shop, to_status: "to_remove"), remote: true, "data-turbolinks" => false, "data-confirm" => "Вы уверены что хотите удалить данный магазин навсегда?", title: "Удалить с сайта" if could_destroy_shop?(shop) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shops/boats_for_sale.html.erb
<%= render "manage_shop_menu" %>
<%= render 'boat_for_sales/form' if could_modify_shop? %>
<% if @boat_for_sales.blank? %>
    <div class = "row tb-pad-s">
        <div class = "small-12 columns">
            <p>
                В магазине нет ни одной лодки
            </p>
        </div>
    </div>    
<%else%>
    <%= react_component 'BFSManageTable', { data: @boat_for_sales} %>
<%end%>

app/views/shops/manage_index.html.erb
<div class = "row" data-toggle style = 'display: none;'>
    <div class = 'small-12 columns'>
        <a class = 'button' onclick = "$('[data-toggle]').toggle(200);">
            Скрыть форму
        </a>
    </div>
    <%= render "form", shop: Shop.new %>
</div>
<div data-toggle >
    <div class = 'row'>
        <div class = 'small-12 columns'>
            <a class = 'button' onclick = "$('[data-toggle]').toggle(200);">
                Добавить магазин
            </a>
        </div>
    </div>
    <% if !@new_shops.blank? %>
        <div class = 'row'>
            <div class = 'small-12 columns'>
                <h3>Недавно добавленные <span data-tooltip aria-haspopup="true" class="has-tip top subheader" data-disable-hover="false" tabindex="2" title="Магазины, которые ожидают подтверждения администратора">?</span></h3>
                <%= render "shops_table", shops: @new_shops %>
            </div>
        </div>
    <% end %>
        <div class = 'row'>
            <div class = 'small-12 columns'>
               <h3>Открытые магазины <span data-tooltip aria-haspopup="true" class="has-tip top subheader" data-disable-hover="false" tabindex="2" title="Магазины, которые могут полноценно использовать сайт, продаваемые ими лодки отображаются в разделах сайта">?</span></h3>
                <% if @opened_shops.blank? %>
                    <p class = "tb-pad-s">
                        Нет ни одного открытого магазина
                    </p>
                <% else %>
                    <%= render "shops_table", shops: @opened_shops %>
                <% end %>
            </div>
        </div>
        <div class = 'row'>
            <div class = 'small-12 columns'>
               <h3>Закрытые магазины <span data-tooltip aria-haspopup="true" class="has-tip top subheader" data-disable-hover="false" tabindex="2" title="Магазины, которые заблокированы своими владельцами, либо по их просьбе, продаваемые ими лодки не отображаются в разделах сайта. Могут быть открыты самим владельцем">?</span></h3>
                <% if @closed_shops.blank? %>
                    <p class = "tb-pad-s">
                        Нет ни одного закрытого магазина
                    </p>
                <% else %>
                    <%= render "shops_table", shops: @closed_shops %>
                <% end %>
            </div>
        </div>
        <div class = 'row'>
            <div class = 'small-12 columns'>
               <h3>Заблокированные магазины <span data-tooltip aria-haspopup="true" class="has-tip top subheader" data-disable-hover="false" tabindex="2" title="Магазины, которые заблокированы администратором, без возможности возобновления активности менеджером, продаваемые ими лодки не отображаются в разделах сайта. Могут быть открыты только администратором">?</span></h3>
                <% if @disabled_shops.blank? %>
                    <p class = "tb-pad-s">
                        Нет ни одного заблокированного магазина
                    </p>
                <% else %>
                    <%= render "shops_table", shops: @disabled_shops%>
                <% end %>
            </div>
        </div>
</div>

app/views/shops/manage_shop_products.html.erb
<%= render "manage_shop_menu" %>
<%= render "shop_products/form" %>
<div class = "row">
    <div class = 'small-12 columns'>
        <table>
            <thead>
                <tr>
                    <th>
                        Название
                    </th>
                    <th>
                        Цена, руб.
                    </th>
                    <th colspan=3>
                    </th>
                </tr>
            </thead>
            <tbody>
                <% if @products.blank? %>
                <tr>
                    <td colspan=5>
                        В магазине нет ни одного товара типа "<%= @product_type.name %>"
                    </td>
                </tr>
                <% else %>
                    <% @products.each do |shop_product| %>
                        <tr>
                            <td>
                                <%= shop_product.product.full_name %>
                            </td>
                            <td>
                                <%= shop_product.amount %>
                            </td>
                            <td>
                                <%= link_to "<i class = 'fi-arrow-right'></i>".html_safe, shop_product_path(id: @shop.id, product_id: shop_product.product_id), target: "_blank" %>
                            </td>
                            <td>
                                
                                <%= link_to "<i class = 'fi-trash'></i>".html_safe, shop_product_path(shop_product), method: :delete, remote: true %>
                            </td>
                            <td>
                                <%#= link_to "<i class = 'fi-trash'></i>".html_safe, delete_product_from_shop, method: :delete, remote: true %>
                            </td>
                        </tr>
                    <%end%>
                <% end %>
                
            </tbody>
        </table>
    </div>
</div>

app/views/shops/manage_show.html.erb
<%= render 'boat_for_sales/form' if could_modify_shop? %>
<% if @boat_for_sales.blank? %>
    <div class = "row tb-pad-s">
        <div class = "small-12 columns">
            <p>
                В магазине нет ни одной лодки
            </p>
        </div>
    </div>    
<%else%>
    <%= react_component 'BFSFilteringResult', { data: @boat_for_sales} %>
<%end%>

app/views/shops/show.html.erb
<% if @boat_for_sales.blank? %>
    <div class = "row tb-pad-s">
        <div class = "small-12 columns">
            <p>
                В магазине нет ни одной лодки
            </p>
        </div>
    </div>    
<%else%>
    <%= react_component 'BFSFilteringResult', { data: @boat_for_sales} %>
<%end%>