config/routes.rb
Rails.application.routes.draw do

  get 'shop_pages/index'

  get 'shop_pages/boats'

  get 'shop_pages/shops'

  get 'photo/show'

  get 'photo/destroy'

  resources :property_types
  post "/copy_property_values", to: "property_types#copy_property_values" #для копирования значений свойств с одного типа лодки или продукта на другой
  
  #products
  resources :products
  get "/manage_products", to: "products#manage_index", as: :manage_products
  #product_types
  resources :product_types
  get "/manage_product_types", to: "product_types#manage_index", as: :manage_product_types
  #boat_type_modifications
  resources :boat_type_modifications, only: [:edit, :update]
  #user_requests
  resources :user_requests
  get "my_boats", to: "user_requests#my_requests", as: :my_boats #мои лодки 
  #shops
  resources :shops
  get "/manage_shops/:id", to: "shops#manage_show", as: :manage_shop                #страница управления магазином
  get "/manage_shops", to: "shops#manage_index", as: :manage_shops                  #управление магазинами
  get "/change_shop_status/:id", to: "shops#change_status", as: :change_shop_status #изменение статуса
  get "/manage_shops/:id/boats_for_sale", to: "shops#boats_for_sale", as: :manage_bfs_in_shop #управление лодками в магазине
  get "/manage_shops/:id/product_types/:product_type_id", to: "shops#manage_shop_products", as: :manage_shop_products #управление товарами магазине
  get "/shops/:id/product_types/:product_type_id", to: "shops#shop_products"
  resources :shop_products, only: [:update, :destroy, :create]
  get "/shops/:shop_id/products/:product_id", to: "shop_products#show", as: :in_shop_product
  
  #shop_products
  


  #end
  #locations
  get "/locations/regions/:country_id", to: "locations#regions"
  get "/locations/cities/:region_id", to: "locations#cities"
  get "/add_country", to: "locations#add_country"
  post "/add_country", to: "locations#add_country"
  #end
  #boat_for_sales
  resources :boat_for_sales
  post "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/manage_boat_for_sale", to: "boat_for_sales#manage_index", as: :manage_boat_for_sales
  get "/boat_for_sales/:id/switch_favorites", to: "boat_for_sales#switch_favorites"
  get "/favorites", to: "boat_for_sales#favorites"
  get "/boat_for_sales/:id/buy", to: "boat_for_sales#buy", as: :buy_bfs
  #end
  #boat_option_types
  resources :boat_option_types, only: [:index, :show, :update]
  #end
  #photos
  resources :photos, only: [:show, :destroy]
  post '/upload_photo/:entity/:entity_id', to: 'photos#upload'
  get "/entity_photos/:entity/:entity_id", to: 'photos#entity_photos'
  put "/entity_photos/:id", to: 'photos#update_entity_photo'
  delete "/entity_photos/:id", to: "photos#destroy_entity_photo" #удаляем ссылки на фотографию от boat_type или product (удаление фотографии)
  
  #end
  get "/test_page", to: "pages#test_page"
  get "/about", to: "pages#about", as: :about
  get "/boats/:id", to: "pages#boat", as: :tm_site_boat
  
  resources :boat_series, only: [:index, :create, :update, :destroy, :show]
  resources :trademarks, only: [:index, :create, :update, :destroy, :show]
  root to: 'pages#index'
  
  
  get "/check_user", to: "users#check", as: :check_user
  get "/cabinet", to: "sessions#current_user_page", as: :my
  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup
  
  #get "/boat_types_import", to: "pages#boat_type_import"
  
  
  resources :sessions, only: [:new, :create]
  
  resources :boat_parameter_values, only: [:update]
  get "/boat_parameter_values/:id/:boat_type_id", to: "boat_parameter_values#switch_bind", as: :switch_bind_parameter_value #привязка-отвязка атрибутов от лодки
  resources :boat_parameter_types, only: [:new, :create, :destroy, :edit, :update, :index]
  post "/reorder_boat_parameter_types", to: "boat_parameter_types#update_numbers"
  
  resources :boat_types, only: [:create, :edit, :update, :destroy, :show]
  post '/boat_types/:id/add_configurator_entity', to: "boat_types#add_configurator_entity"  
  get "/manage_boat_types", to: "boat_types#manage_index", as: :manage_boat_types
  get '/boat_types/:id/photos', to: "boat_types#photos", as: :boat_type_photos
  get '/boat_types/:id/videos', to: 'boat_types#videos', as: :boat_type_videos
  get '/boat_types/:id/photos/:photo_id', to: "boat_types#photo", as: :boat_photo
  get '/boat_types/:id/property_values', to: 'boat_types#property_values'
  get '/boat_types/:id/modifications/:modification_id', to: 'boat_types#modification_show', as: :modification
  put '/boat_types/:id/property_values', to: 'boat_types#update_property_values'
  post '/boat_types/:id/modifications', to: 'boat_types#create_modification'
  get '/boat_types/:id/modifications', to: 'boat_types#modifications', as: :boat_type_modifications
  get '/get_boat_types_list', to: 'boat_types#get_boat_types_list'
  post "/copy_photos", to: "boat_types#copy_photos"
  get '/boat_types/:id/options', to: "boat_types#options", as: :boat_type_options
  resources :users
  
  resources :boat_property_types, only: [:index, :create] 
  
  #Realcraft Part--------------------------------------------------------------------------------------
  #get 'about', to: 'realcraft#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "realcraft_pages#dealers", as: :realcraft_dealers
  get 'realcraft190', to: 'realcraft_pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'realcraft_pages#realcraft_200', as: :realcraft_200
  get "wait", to: 'realcraft_pages#please_wait', as: :realcraft_wait
  get "about_realcraft", to: 'realcraft_pages#about', as: :realcraft_about
  post "send_boat_request", to: 'realcraft_pages#send_boat_request', as: :realcraft_send_boat_request
  post "send_dealer_request", to: 'realcraft_pages#send_dealer_request', as: :realcraft_send_dealer_request
  
  
  #videos Part
  resources :videos, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/boat_types_controller.rb
class BoatTypesController < ApplicationController
  before_action :check_grants, only: [:create, :edit, :update, :destroy, :manage_index, :update_property_values, :create_modification]
  before_action :set_boat_type, only: [:show, :options, :modification_show,:edit, :update, :destroy, :add_configurator_entity, :update_property_values, :property_values, :create_modification, :photos, :modifications, :videos]
  before_action :set_trademarks_and_boat_series, only: [:show, :manage_index]

  def manage_index
    @title = "Управление типами лодок"
    @boat_types = BoatType.base_types.to_a.map{ |bt| bt.hash_view('control')}
    @data = {boat_types: @boat_types, boat_series_list: @boat_series, trademarks: @trademarks}
  end
  
  # GET /boat_types
  # GET /boat_types.json
  
  def index
    @boat_types = params[:ids].blank? ? BoatType.active : BoatType.where(id: params[:ids])
    if params[:ids].blank? 
      @boat_types = BoatType.active
      #parameter_filter_data = BoatParameterType.filter_data
      #option_filter_data = BoatOptionType.filter_data 
     # @filter_data = parameter_filter_data.merge(option_filter_data)
     # @default_boats = BoatForSale.active.ids 
    else
      @boat_types = BoatType.with_bfs.where(id: params[:ids])
    end
  end

  # GET /boat_types/1
  # GET /boat_types/1.json
  def show
    @title = @header = @boat_type.catalog_name 
    
    #@data = is_control? ? {boat_type: @boat_type.hash_view(current_site, cur_locale.to_s), trademarks: @trademarks, boat_series: @boat_series} : {boat_type: @boat_type}
    respond_to do |format|
      format.html 
      format.json { render json: @data}
    end
  end
  
  def photos
    @title = @boat_type.catalog_name
    photos = @boat_type.entity_photos.map {|ph| ph.hash_view}
    @data = is_control? ? {boat_type: @boat_type.hash_view(current_site, cur_locale.to_s), photos: photos, form_token: form_authenticity_token} : photos
    respond_to do |format|
      format.html {render "show"}
      format.json {render json: @data}
    end
  end
  
  def modifications
    @title = @header = @boat_type.catalog_name + ": Компоновки"
    modifications = @boat_type.modifications.to_a.map{|m| m.hash_view(current_site, cur_locale.to_s)}
    @data = is_control? ? {boat_type: @boat_type.hash_view(current_site, cur_locale.to_s), modifications: modifications, form_token: form_authenticity_token} : modifications
    respond_to do |format|
      format.html
      format.json {render json: @data}
    end
  end
  
  def videos
    @title = @header = @boat_type.catalog_name + ": Видео"
    respond_to do |format|
      format.html
    end
  end
  
  #GET /boat_types/:boat_type_id/modifications/:id
  def modification_show
    @modification = @boat_type.modifications.find_by(id: params[:modification_id])
    if @modification.nil?
      redirect_to '/404' 
    else
      render json: @modification.hash_view(current_site, cur_locale)
    end
  end
  
  def options
    @title = @header = @boat_type.catalog_name + ": Опции"
  end

  # GET /boat_types/1/edit
  def edit
    @title = @header = "Редактирование типа лодки"
    @confFileExists = @boat_type.remote_cnf_file_exists?
    @additionScript = @boat_type.cnf_data_file_url if @confFileExists
    @modifications = @boat_type.check_modifications
    @property_values = @boat_type.entity_property_values
  end
  
  #POST /add_configurator_entity - сюда присылаем опции для добавления в бд
  def add_configurator_entity
    ent = []
    if @boat_type.update_attributes(configurator_entities_params)
      render json: {status: :ok}
      @boat_type.create_local_cnf_file
    else
      render json: {status: :failed}
    end
  end

  # POST /boat_types
  # POST /boat_types.json
  def create
    @boat_type = BoatType.new(boat_type_params)
    respond_to do |format|
      if @boat_type.save
        format.html { redirect_to edit_boat_type_path(@boat_type)}
        format.json { render json: @boat_type.hash_view('control'), status: :created, location: @boat_type }
      else
        format.html { render :new }
        format.json { render json: @boat_type.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #POST /boat_types/1/modifications
  def create_modification
    @modification = @boat_type.modifications.build(modification_params)
    respond_to do |format|
      if @modification.save
        format.json { render json: @modification.hash_view('control'), status: :created}
      else
        format.json { render json: @modification.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /boat_types/1
  # PATCH/PUT /boat_types/1.json
  def update
    prms = @boat_type.is_modification? ? modification_params : boat_type_params
    respond_to do |format|
      if @boat_type.update(prms)
        format.html { redirect_to edit_boat_type_path(@boat_type), notice: 'Тип лодки успешно обновлён' }
        format.json { render json: @boat_type.hash_view('control'), status: :ok}
      else
        format.html { render :edit }
        format.json { render json: @boat_type.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def property_values
      render json: @boat_type.property_values_hash(cur_locale.to_s) if !is_control?
      render json: @boat_type.property_values_hash if is_control?
  end
  
  # PATCH/PUT /boat_types/1/property_values
  def update_property_values
    respond_to do |format|
      if @boat_type.update(boat_properties_params)
        format.json {render json: @boat_type.property_values_hash}
      else
        format.json {render json: {message: 'Не удалось обновить таблицу характеристик'}, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /boat_types/1
  # DELETE /boat_types/1.json
  def destroy
    if !@boat_type.is_modification?
      @boat_type.destroy
      respond_to do |format|
        format.html { redirect_to manage_boat_types_url, notice: 'Тип лодки был успешно удалён' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        if @boat_type.boat_type.modifications.size > 1 
          @boat_type.destroy
          format.json { head :no_content }
        else
          format.json {render json: {message: 'Нельзя удалить компоновку, если она единственная'}, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def get_boat_types_list
    listType = params[:type].blank? ? 'properties' : params[:type]
    mdfs = BoatType.all_modifications
    mdfs = listType == "photos" ? mdfs.map {|m| {id: m.id, name: m.catalog_name} if !m.photos.blank?} : mdfs.map {|m| {id: m.id, name: m.catalog_name}}
    mdfs.compact!
    render json: mdfs.to_json
  end
  
  def copy_photos
    prms = copy_params
    copy_from = BoatType.find_by(id: prms[:copy_from])
    copy_to = BoatType.find_by(id: prms[:copy_to])
    if !copy_from.nil? and !copy_to.nil?
      photos = copy_to.copy_photos_from(copy_from)
      photos = photos.map {|ph| ph.hash_view}
      render json: photos
    else
      render json: []
    end
   
  end
  
  def copy_properties
    prms = copy_params
    copy_from = BoatType.find_by(id: prms[:copy_from])
    copy_to = BoatType.find_by(id: prms[:copy_to])
    if !copy_from.nil? and !copy_to.nil?
      photos = copy_to.copy_properties_from(copy_from)
      photos = photos.map {|ph| ph.hash_view}
      render json: photos
    else
      render json: []
    end
    
  end
  
  private
    def check_grants
      redirect_to "/404" if !could_manage_boat_types? || !is_control?
    end 
    # Use callbacks to share common setup or constraints between actions.
    def set_boat_type
      #boat_type = 
      #redirect_to boat_type.boat_type and return if boat_type.is_modification? 
      @boat_type = BoatType.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_type_params
      params.require(:boat_type).permit(:ru_name, :en_name, :design_category, :copy_params_table_from_id, :boat_series_id, :body_type, :ru_description, :en_description, :ru_slogan, :en_slogan, :cnf_data_file_url, :base_cost, :is_deprecated, :is_active, :trademark_id, :use_on_ru, :use_on_en)
    end
    
    def modification_params
      params.require(:boat_type).permit(:top_view, :aft_view, :bow_view, :accomodation_view_1, :accomodation_view_2, :accomodation_view_3, :delete_view, :ru_name, :en_name, :ru_description, :en_description, :is_deprecated, :is_active, :use_on_ru, :use_on_en)
    end
    
    def boat_properties_params
      params.require(:boat_type).permit(entity_property_values_attributes: [:property_type_id, :is_binded, :set_ru_value, :set_en_value])
    end
    
    def copy_params
      params.require(:copy_entities).permit(:copy_from, :copy_to)
    end
    
    def configurator_entities_params
      params.require(:boat_type).permit(configurator_entities_attributes: [
        :arr_id,
        :rec_type,
        :rec_level,
        :hidden,
        :group_hidden, 
        :rec_fixed_invisibility,
        :param_code,
        :param_name,
        :comment,
        :nom_std_compl,
        :checked,
        :level_checked,
        :enabled,
        :start_enabled,
        :std_comp_sostav,
        :std_comp_option,
        :std_comp_select,
        :std_comp_enable,
        :std_comp_prefer,
        :sel_if_y,
        :sel_if_n, 
        :de_sel_if_y,
        :de_sel_if_n, 
        :en_if_y, 
        :en_if_n, 
        :dis_if_y, 
        :dis_if_n, 
        :price, 
        :amount])
    end
    
    def set_trademarks_and_boat_series
      return unless is_control?
      @trademarks = Trademark.all
      @boat_series = BoatSeries.all
    end
end

app/helpers/boat_types_helper.rb
module BoatTypesHelper

end

app/views/boat_types/_boat_types_table.html.erb
<% if boat_types.blank? %>
    <p>
        Список лодок пуст
    </p>
<%else%>
    <table>
      <thead>
        <tr>
          <th>Торговая марка</th>
          <th>Серия</th>
          <th>Тип корпуса</th>
          <th>Название</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% boat_types.each do |boat_type| %>
          <tr>
            <td><%= link_to boat_type.trademark.name, boat_type.trademark %></td>
            <td><%= boat_type.boat_series.name if !boat_type.boat_series.nil? %></td>
            <td><%= boat_type.body_type %></td>
            <td><%= boat_type.name %></td>
            <td><%= link_to "<i class = 'fi-arrow-right'></i>".html_safe, boat_type_path(boat_type) %></td>
            <td><%= link_to "<i class = 'fi-x'></i>".html_safe, boat_type, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить данный тип лодки?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%end%>

app/views/boat_types/_form.html.erb
<div class = "row">
    <div class = "small-12 columns">
        <%= form_for(boat_type) do |f| %>
          <% if boat_type.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(boat_type.errors.count, "error") %> prohibited this boat_type from being saved:</h2>

              <ul>
              <% boat_type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <% if !boat_type.new_record? %>
          <div class = "row">
              <div class="small-2 columns field">
                <%= f.label :design_category, "Класс лодки" %>
                <%= f.text_field :design_category %>
              </div>
              <div class="small-2 columns field">
                <%= f.label :is_deprecated, "Устаревшая модель" %>
                <%= f.check_box :is_deprecated %>
              </div>
              
              <div class="small-2 columns end field">
                <%= f.label :is_active, "Показывать в каталоге" %>
                <%= f.check_box :is_active %>
              </div>
          </div>
          <%end%>
          <div class = "row">
              <div class="small-3 columns field">
                <%= f.label :trademark_id, "Марка лодки" %>
                <%= f.collection_select :trademark_id, Trademark.all, :id, :name %>
              </div>
          
              <div class="small-3 columns field">
                  <%= f.label :boat_series_id, "Серия" %>
                  <%= f.collection_select :boat_series_id, BoatSeries.all, :id, :name, include_blank:  "Вне серии"  %> 
              </div>
              
              <div class="small-3 columns field">
                <%= f.label :body_type, "Корпус" %>
                <div class = "row">
                    <div class="small-6 columns field">
                        <%= f.text_field :body_type %>
                    </div>
                    <div class="small-6 columns field">
                        <%= my_select_list(BoatType.body_types, "boat_type_body_type") %>
                    </div>
                </div>
              </div>
              
              <div class="small-3 columns field">
                <%= f.label :name, "Название лодки" %>
                <%= f.text_field :name %>
              </div>
          </div>
          <% if !boat_type.new_record? %>
          <div class="field">
            <%= f.label :cnf_data_file_url, "Ссылка на файл конфигуратора" %>
            <%= f.text_field :cnf_data_file_url %>
          </div>

          <%else%>
              <div class = 'row'>      
                  <div class="small-4 columns field tb-pad-s">
                    <%= f.label :copy_params_table_from_id, "Копировать таблицу параметров из: " %>
                    <%= f.collection_select :copy_params_table_from_id, BoatType.all, :id, :catalog_name, include_blank:  "У этого типа свои параметры"  %> 
                  </div>
              </div>
          <%end%>
          <% if !boat_type.new_record? %>
              <div class = 'row'>      
                  <div class="small-12 columns field tb-pad-s">
                      <% if boat_type.entity_property_values.count > 0 %>
                          <%= render "property_types/property_values_table", form: f, property_values: boat_type.entity_property_values %>
                      <% else %>
                         <p>
                             Для лодок нет ни одной характеристики
                         </p>
                      <% end %>
                  </div>
              </div>
          <%end%>
          <div class="actions button-group tb-pad-s">
            <button class = "success button" type = "submit">
                <% if boat_type.new_record? %>
                    Создать
                <%else%>
                    Сохранить изменения
                <%end%>
            </button>
            <button class = "secondary button" type = "reset">
                Отменить изменения
            </button>
          </div>
        <% end %>
    </div>
</div>

app/views/boat_types/_manage_show_menu.html.erb
 <div class = 'row'>
     <div class = 'small-12 columns tb-pad-s'>
         <ul class = "menu right-menu">
             <li>
                 <%= link_to "Основная информация", @boat_type %>
             </li>
             <li>
                 <%= link_to "Видео", boat_type_videos_path(@boat_type) %>
             </li>
             <li>
                 <%= link_to "Компоновки", boat_type_modifications_path(@boat_type) %>
             </li>
             <li>
                 <%= link_to "Список опций", boat_type_options_path(@boat_type) %>
             </li>
         </ul>
     </div>
 </div> 

app/views/boat_types/edit.html.erb
<% @boat_type.errors.each do |e| %>
    <br /><%= e %>
<%end%>

app/views/boat_types/manage_index.html.erb
<%= react_component 'BoatTypesManageIndex', @data %>

app/views/boat_types/modifications.html.erb
<%= render "manage_show_menu" %>
<%= react_component "BoatTypeModifications", @data %>

app/views/boat_types/new.html.erb
<%= render 'control' %>

app/views/boat_types/options.html.erb
<%= render "manage_show_menu" %>
<%# react_component "BoatTypeVideos", {videos: @boat_type.boat_videos, boat_type_id: @boat_type.id} %>

app/views/boat_types/photo.html.erb
<%= image_tag @photo.link.small%>
<%= image_tag @photo.link.medium%>
<%= image_tag @photo.link.large%>

app/views/boat_types/show.html.erb
<%= render "manage_show_menu" %>

<%= react_component 'BoatMainInfo', {boat_type: @boat_type, trademarks: @trademarks, boat_series: @boat_series} %>

<!-- 


<div class = "row tb-pad-m">
    <div class = "small-12 columns">
        <ul class = 'bb-inline-menu' data-match-height = "true" data-tabs id="bb-tabs" data-deep-link="false" data-turbolinks="false">
            <li class = 'tabs-title is-active'>
                <a href="#technical" >Технические характеристики</a>
            </li>

            <li class = 'tabs-title '>
               <a href="#photos" onclick = "getPhotos(<%# @boat_type.id %>);">Фото</a>
            </li>
        </ul>
    </div>
</div>

<div class = "tabs-content"  data-tabs-content="bb-tabs">
    <div class = 'tabs-panel is-active' id="main">
        
    </div>
    <div class = 'tabs-panel'  id="technical">
       <div class = "row">
           <div class = "small-12 columns">
               <%# react_component 'BoatParameterValuesTableShow', { data: @boat_type.boat_parameters_for_react } %>
           </div>
       </div>
    </div>
    <div class = 'tabs-panel'  id="photos">

    </div>
</div>


<%= link_to 'Edit', edit_boat_type_path(@boat_type) %> |
<%= link_to 'Back', boat_types_path %>
-->

app/views/boat_types/videos.html.erb
<%= render "manage_show_menu" %>
<%= react_component "BoatTypeVideos", {videos: @boat_type.boat_videos, boat_type_id: @boat_type.id} %>