config/routes.rb
Rails.application.routes.draw do

  get 'shop_pages/index'

  get 'shop_pages/boats'

  get 'shop_pages/shops'

  get 'photo/show'

  get 'photo/destroy'

  resources :property_types
  post "/copy_property_values", to: "property_types#copy_property_values" #для копирования значений свойств с одного типа лодки или продукта на другой
  
  #products
  resources :products
  get "/manage_products", to: "products#manage_index", as: :manage_products
  #product_types
  resources :product_types
  get "/manage_product_types", to: "product_types#manage_index", as: :manage_product_types
  #boat_type_modifications
  resources :boat_type_modifications, only: [:edit, :update]
  #user_requests
  resources :user_requests
  get "my_boats", to: "user_requests#my_requests", as: :my_boats #мои лодки 
  #shops
  resources :shops
  get "/manage_shops/:id", to: "shops#manage_show", as: :manage_shop                #страница управления магазином
  get "/manage_shops", to: "shops#manage_index", as: :manage_shops                  #управление магазинами
  get "/change_shop_status/:id", to: "shops#change_status", as: :change_shop_status #изменение статуса
  get "/manage_shops/:id/boats_for_sale", to: "shops#boats_for_sale", as: :manage_bfs_in_shop #управление лодками в магазине
  get "/manage_shops/:id/product_types/:product_type_id", to: "shops#manage_shop_products", as: :manage_shop_products #управление товарами магазине
  get "/shops/:id/product_types/:product_type_id", to: "shops#shop_products"
  resources :shop_products, only: [:update, :destroy, :create]
  get "/shops/:shop_id/products/:product_id", to: "shop_products#show", as: :in_shop_product
  
  #shop_products
  


  #end
  #locations
  get "/locations/regions/:country_id", to: "locations#regions"
  get "/locations/cities/:region_id", to: "locations#cities"
  get "/add_country", to: "locations#add_country"
  post "/add_country", to: "locations#add_country"
  #end
  #boat_for_sales
  resources :boat_for_sales
  post "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/manage_boat_for_sale", to: "boat_for_sales#manage_index", as: :manage_boat_for_sales
  get "/boat_for_sales/:id/switch_favorites", to: "boat_for_sales#switch_favorites"
  get "/favorites", to: "boat_for_sales#favorites"
  get "/boat_for_sales/:id/buy", to: "boat_for_sales#buy", as: :buy_bfs
  #end
  #boat_option_types
  resources :boat_option_types, only: [:index, :show, :update]
  #end
  #photos
  resources :photos, only: [:show, :destroy]
  post '/upload_photo/:entity/:entity_id', to: 'photos#upload'
  get "/entity_photos/:entity/:entity_id", to: 'photos#entity_photos'
  put "/entity_photos/:id", to: 'photos#update_entity_photo'
  delete "/entity_photos/:id", to: "photos#destroy_entity_photo" #удаляем ссылки на фотографию от boat_type или product (удаление фотографии)
  
  #end
  get "/test_page", to: "pages#test_page"
  get "/about", to: "pages#about", as: :about
  get "/boats/:id", to: "pages#boat", as: :tm_site_boat
  
  resources :boat_series, only: [:index, :create, :update, :destroy, :show]
  resources :trademarks, only: [:index, :create, :update, :destroy, :show]
  root to: 'pages#index'
  
  
  get "/check_user", to: "users#check", as: :check_user
  get "/cabinet", to: "sessions#current_user_page", as: :my
  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup
  
  #get "/boat_types_import", to: "pages#boat_type_import"
  
  
  resources :sessions, only: [:new, :create]
  
  resources :boat_parameter_values, only: [:update]
  get "/boat_parameter_values/:id/:boat_type_id", to: "boat_parameter_values#switch_bind", as: :switch_bind_parameter_value #привязка-отвязка атрибутов от лодки
  resources :boat_parameter_types, only: [:new, :create, :destroy, :edit, :update, :index]
  post "/reorder_boat_parameter_types", to: "boat_parameter_types#update_numbers"
  
  resources :boat_types, only: [:create, :edit, :update, :destroy, :show]
  post '/boat_types/:id/add_configurator_entity', to: "boat_types#add_configurator_entity"  
  get "/manage_boat_types", to: "boat_types#manage_index", as: :manage_boat_types
  get '/boat_types/:id/photos', to: "boat_types#photos", as: :boat_type_photos
  get '/boat_types/:id/videos', to: 'boat_types#videos', as: :boat_type_videos
  get '/boat_types/:id/photos/:photo_id', to: "boat_types#photo", as: :boat_photo
  get '/boat_types/:id/property_values', to: 'boat_types#property_values'
  get '/boat_types/:id/modifications/:modification_id', to: 'boat_types#modification_show', as: :modification
  put '/boat_types/:id/property_values', to: 'boat_types#update_property_values'
  post '/boat_types/:id/modifications', to: 'boat_types#create_modification'
  get '/boat_types/:id/modifications', to: 'boat_types#modifications', as: :boat_type_modifications
  get '/get_boat_types_list', to: 'boat_types#get_boat_types_list'
  post "/copy_photos", to: "boat_types#copy_photos"
  get '/boat_types/:id/options', to: "boat_types#options", as: :boat_type_options
  resources :users
  
  resources :boat_property_types, only: [:index, :create] 
  
  #Realcraft Part--------------------------------------------------------------------------------------
  #get 'about', to: 'realcraft#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "realcraft_pages#dealers", as: :realcraft_dealers
  get 'realcraft190', to: 'realcraft_pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'realcraft_pages#realcraft_200', as: :realcraft_200
  get "wait", to: 'realcraft_pages#please_wait', as: :realcraft_wait
  get "about_realcraft", to: 'realcraft_pages#about', as: :realcraft_about
  post "send_boat_request", to: 'realcraft_pages#send_boat_request', as: :realcraft_send_boat_request
  post "send_dealer_request", to: 'realcraft_pages#send_dealer_request', as: :realcraft_send_dealer_request
  
  
  #videos Part
  resources :videos, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/realcraft_pages_controller.rb
class RealcraftPagesController < ApplicationController
  include RealcraftHelper 
  before_action :check_request_forms, only: [:send_boat_request, :send_dealer_request]
  
  def index
  end

  def prices
    @title = t(:prices)
  end
  
  def dealers
    @title = t(:dealers)
  end
  
  def about
    @title = t(:about)
  end
  
  def realcraft_190
    @boat = real_craft_190
    @title = @boat[:name]
    @page_image = '/slider/rc190/2_xlarge.jpg'
    @meta_content = @boat["slogan_#{cur_locale}".to_sym]
  end

  def realcraft_200
    @boat = real_craft_200
    @title = @boat[:name]
    @page_image = '/slider/rc200/4_slider_xlarge.jpg'
    @meta_content = @boat["slogan_#{cur_locale}".to_sym]
  end
  
  def send_boat_request
    #redirect_to "/404" if params[:boat_request].blank?
    render js: %{$("#success-request").show();} if RequestsMailer.boat_request(boat_request_params).deliver_now && RequestsMailer.boat_request(boat_request_params, "romankozvonin@gmail.com").deliver_now
  end
  
  def send_dealer_request
    #redirect_to "/404" if params[:dealer_request].blank?
    render js: %{$("#success-request").show();} if RequestsMailer.dealer_request(dealer_request_params).deliver_now && RequestsMailer.dealer_request(dealer_request_params, "romankozvonin@gmail.com").deliver_now
  end
  
  def please_wait
    #redirect_to root_path if (cur_locale == "ru" && $enable_ru_locale) || (cur_locale == "en" && $enable_en_locale) 
  end
  
  private 
  
  def check_request_forms
    f = false
    if !params[:boat_request].blank?
      f = !params[:boat_request][:email].blank? && !params[:boat_request][:name].blank? 
    else !params[:dealer_request].blank?
      f = !params[:dealer_request][:email].blank? && !params[:dealer_request][:name].blank? 
    end
    redirect_to "/404" if !f
  end
  
  def boat_request_params
    params.require(:boat_request).permit(:name, :email, :boat_name, :comment)
  end
  
  def dealer_request_params
    params.require(:dealer_request).permit(:name, :email, :comment)
  end
end

app/views/realcraft_pages/_boat_params_table.html.erb
<% 
    if @boat.nil? 
        canDrawTable = false
    else
        canDrawTable = !@boat[:boat_parameters].blank?
    end
%>
<%if canDrawTable %>
<% 
    mdfs = @boat[:modifications] 
%>
<div class = "row tb-pad-s">
    <div class = "small-12 columns">
        <h3 class = 'tb-pad-s'>
            <%= t :parameters_table %>
        </h3>
        <table class="hover">
            <thead>
            <tr>
                <th>
                    <%= t :parameter_name %>
                </th>
                <% mdfs.each do |m| %>
                    <th id = "modification">
                        <%= "#{@boat[:name]} #{m[:name] }"%>
                    </th>
                <% end %>
            </tr>
            </thead>
            <tr>
                <td>
                    <%= t :design_category %>
                </td>
                <td align = "center" colspan = "<%= mdfs.length %>">
                    <%= @boat[:design_category]%>
                </td>
            </tr>
            <% @boat[:boat_parameters].each do |p| %>
            <tr>
                <td>
                    <% if !p[:notice].blank? %> 
                        <span data-tooltip aria-haspopup="true" class="has-tip top" data-disable-hover="false" tabindex="2" title="<%= p[:notice] %>">
                            <%= p[:title] %> 
                        </span> 
                    <%else%>
                        <%= p[:title] %> 
                    <%end%>
                </td>
                <% if p[:value].class.name == "Array" %>
                    <% 0.upto(mdfs.length-1) do |i| %>
                        <td align = "center" >
                            <% if i < p[:value].length %>
                                <%= p[:value][i] %><%= p[:unit] %>
                            <% else %>
                                -
                            <%end%>
                        </td>
                    <%end%>
                <%else%>
                    <td align = "center" colspan = <%= mdfs.length %>>
                        <%= p[:value] %><%= p[:unit] %>
                    </td>
                <%end%>
            </tr>
            <%end%>
        </table>
    </div>
</div>
<%end%>

app/views/realcraft_pages/_boat_request_form.html.erb
    <div class="reveal" data-reveal id = "boat-form-container">
        <div class = "tb-pad-s">
            <div class = "row">
                <div class = "small-10 small-centered columns">
                    <h4>
                        <%= t(:boat_request) %>
                    </h4>
                </div>
            </div>
            <div style = "display: none;" id = 'success-request' class = "row">
                <div class = "small-10 small-centered columns">
                    <div class = 'callout success'>
                    <p>
                        <i class = 'fi-check'></i> <%= t(:successfull_boat_request) %>
                    </p>
                   </div>
                </div>
            </div>
            <%= form_for(:boat_request, url: realcraft_send_boat_request_path, html: {"data-abide"=> "", novalidate: "", remote: true}) do |f| %>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <div class = "row">
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :email, "E-mail" %>
                                <%= f.email_field :email, placeholder: "name@domain.com", required: true  %>
                                <span class="form-error">
                                    <%= t(:fail_mail_msg)%>
                                </span>
                            </div>
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :name, t(:mail_name) %>
                                <%= f.text_field :name, placeholder: t(:name_example), required: true  %>
                                <span class="form-error">
                                    <%= t(:mail_name_error)%>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <%= f.label :boat_name, t(:mail_boat) %>
                        <%= f.select :boat_name, boats_for_request_form if is_boat_page != true %>
                        <%= f.text_field :boat_name, readonly: '' if is_boat_page == true %>
                    </div>
                </div>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <%= f.label :comment, t(:mail_comment) %>
                        <%= f.text_area :comment, rows: 4 %>
                    </div>
                </div>
                <div class = 'row'>
                    <div class = "small-10 small-centered columns">
                        <%= f.submit t(:send_request_mail), class: "button success" %>
                    </div>
                </div>
            <% end %>
        </div>
        <button class="close-button" data-close type="button">
           <span aria-hidden="true">&times;</span>
        </button>
    </div>

app/views/realcraft_pages/_dealer_request_form.html.erb
    <div class="reveal" data-reveal id = "dealer-form-container">
        <div class = "tb-pad-s">
            <div class = "row">
                <div class = "small-10 small-centered columns">
                    <h4>
                        <%= t(:dealer_request) %>
                    </h4>
                </div>
            </div>
            <div style = "display: none;" id = 'success-request' class = "row">
                <div class = "small-10 small-centered columns">
                    <div class = 'callout success'>
                    <p>
                        <%= t(:successfull_boat_request) %>
                    </p>
                   </div>
                </div>
            </div>
            <%= form_for(:dealer_request, url: realcraft_send_dealer_request_path, html: {"data-abide"=> "", novalidate: "", remote: true}) do |f| %>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <div class = "row">
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :email, "E-mail" %>
                                <%= f.email_field :email, placeholder: "name@domain.com", required: true  %>
                                <span class="form-error">
                                    <%= t(:fail_mail_msg)%>
                                </span>
                            </div>
                            <div class = "small-12 medium-6 columns">
                                <%= f.label :name, t(:mail_name) %>
                                <%= f.text_field :name, placeholder: t(:name_example), required: true  %>
                                <span class="form-error">
                                    <%= t(:mail_name_error)%>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class = "row">
                    <div class = "small-10 small-centered columns">
                        <%= f.label :comment, t(:mail_comment) %>
                        <%= f.text_area :comment, rows: 4 %>
                    </div>
                </div>
                <div class = 'row'>
                    <div class = "small-10 small-centered columns">
                        <%= f.submit t(:send_request_mail), class: "button success" %>
                    </div>
                </div>
            <% end %>
        </div>
        <button class="close-button" data-close type="button">
           <span aria-hidden="true">&times;</span>
        </button>
    </div>

app/views/realcraft_pages/_footer.html.erb
<div class = "light-gray-block">
    <div id = "footer" class = "row tb-pad-m">
        <div id = "footer-logo" class = "small-12 medium-5 columns">
            <div class = "row">
                <div class = "small-12 small-push-12 medium-push-0 columns">
                   <%= image_tag "realcraft_logo_colorful.png" %>
                </div>
            </div>
            <div class = "row tb-pad-m">
                <div class = "small-12 small-pull-12 medium-pull-0 columns">
                    REALCRAFT™, 2014-<%= Time.now.year.to_s %> 
                </div>
            </div>
        </div>
        <div id = "footer-contacts"  class = "small-12 medium-offset-1 medium-6 columns">
            <h4>
                <%= t(:contacts) %>
            </h4>
            <p>
                <% if cur_locale == :en%>
                Samara Motor-Boat Plant «Salut» (Salut-boats Ltd),<br />
                Sovetskaya str., 38L, Novosemeykino urban-type settlement, Krasnoyarskiy district,<br />
                Samara region, Russia, 446379, <br />
                Tel.:  +7-846-9726801, +7-846-277210<br />
                <%else%>
                Самарский завод моторных лодок «СAЛЮТ»,<br />
                Россия, 446379, Самарская область, Красноярский район,<br />
                пгт. Новосемейкино, ул. Советская, д. 38л<br />
                Тел.:  +7-846-9726801, +7-846-277210<br />
                <%end%>
                <%= link_to t(:self_url_name), root_path %><br />
                <%= mail_to "info@realcraftboats.com", "info@realcraftboats.com" %>
            </p>
        </div>
    </div>

</div>

app/views/realcraft_pages/_simple_pages_content.html.erb
<%if !content.blank? %>
    <% content.each do |row| %>
        <div <%= row[:is_hidden] == true ? "style=display:none;" : "" %> <%= row[:wrapper_bg_image].blank? ? "" : "data-interchange = '#{make_photos_interchange(wrapper_bg_image(row[:wrapper_bg_image]))}' style = 'background-image: url(\"#{wrapper_bg_image(row[:wrapper_bg_image])}\");'".html_safe %> class = "c-box <%= row[:wrapper_class].blank? ? "" : "#{row[:wrapper_class]}" %>">
            <% if !row[:fog_class].blank? %>
                <div class = "rc-fog <%= row[:fog_class] %>">
                </div>
            <% end %>
            <div style = 'position: relative; z-index:  500;' class = "row <%= row[:row_class].nil? ? "" : row[:row_class] %>">
                <%if !row[:columns].empty?%>
                    <%row[:columns].each do |c|%>
                        <div class = "<%= c[:col_class].blank? ? "small-12" : c[:col_class] %> columns">
                            <p>
                                <%= c["#{cur_locale}_content".to_sym].html_safe if !c["#{cur_locale}_content".to_sym].blank? %>
                                <%= c[:content].html_safe if !c[:content].blank? %>
                            </p>
                        </div>
                    <%end%>
                <%end%>
            </div>
        </div>
    <%end%>
<%end%>

app/views/realcraft_pages/dealers.html.erb
<div class = "tb-pad-s">
    <div class = "row">
        <div class = "small-12 columns">
            <%= rc_header(t(:dealers))  %>
        </div>
    </div>
</div>

<%= render "simple_pages_content", content: dealers_page_content %>

<div id = "boat-request-form" style = 'display: none;'>
    <%= render "dealer_request_form" %>
</div>

app/views/realcraft_pages/index.html.erb
<div class="orbit" role="region" aria-label="RealCraft Motor Boats" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
  <div id = "slogan">
      <div class = 'row tb-pad-s' style = " position: relative;margin-left: auto; margin-right: auto;">
         <div class = "small-12 columns">
             <img id = "slogan-img" src = "/realcraft_files/files/main_slogan.png">
         </div>
      </div>
  </div>
    <div class="orbit-container">
      <%= slider_imgs(main_page_slider_imgs).html_safe  %>
    </div>
</div> 
<div class = "light-gray-block">
    <div class = 'row'>
        <div class = 'small-12 columns tb-pad-s'>
            <a href = "/realcraft_files/files/Realcraft.pdf" target = '_blank' class = 'button rc-blue expanded' style = "margin: 0 0 0 0;"><i class = 'fi-download'></i> <%= t(:download_brochure).mb_chars.upcase %></a>
        </div>
    </div>
</div>  
<!--boats list-->
<% if !hash_boats_list.blank?%>
    <%j=0%>
    <% hash_boats_list.each do |b|%>
    <%j+=1%>
    <div class = "pages-index-boat-item ">
        <div class = "<%= j.odd? ? "odd" : "even"  %>-wrapper"></div>
        <div class = "content tb-pad-s">
            <div class = "row tb-pad-s">
                <div class = "small-12 medium-5 columns">
                    <%= rc_header(b[:name], t(:model), "#{t :design_category} #{b[:design_category]}") %>
                </div>
                <div class = "small-12 medium-7 columns">
                    <% if !b[:index_page_parameters].blank?%>
                        <div class = "row">
                        <% b[:index_page_parameters].each do |i|%>
                            <div class = "small-4 columns params-list">
                                <p class = "rc-param-name-s text-center">
                                    <%= b[:boat_parameters][i][:title] %>
                                </p>
                                <div class="stat text-center rc-param-val-s">
                                    <%= b[:boat_parameters][i][:value] %><%= b[:boat_parameters][i][:unit] %>
                                </div>
                            </div>
                        <%end %>
                        </div>
                    <%end %>
                </div>
            </div>
            <div class = "row">
                <div class = "small-12 columns text-center">
                    <p >
                        <%= b["slogan_#{cur_locale}".to_sym] %>
                    </p>
                </div>
            </div>
            <div class = "row tb-pad-s">
                <div class = "small-12 columns">
                    <%= image_tag b[:slider_images].first, "data-interchange".to_sym => make_photos_interchange(b[:slider_images].first), style: "padding:0; margin:0;", vspace: "0" %>
                    <div class = "tb-pad-s">
                    <%= link_to ("<i class = \"fi-arrow-right\"></i> #{t(:go_to_item, item: b[:name])}").html_safe, b[:url], class: "rc-primary-blue button expanded large" %>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
    <%end%>
<%end%>
<!--boats list end-->
<div class = "light-blue-block">
    <div class = "tb-pad-m">
        <div class = "row">
            <div class = "small-12 columns text-center">
                <%= rc_header(t(:we_are), t(:who)) %>
            </div>
        </div>
        <div class = "row">
            <div class = "small-12 medium-4 columns">
                <p class = "stat text-center">
                     15,000 <%= t :m_short %><span class = "degree">2</span>
                 </p>
                 <p class = "rc-param-name-b text-center">
                     <%= t :land_for_production %>
                 </p>
                 <a><%= image_tag production_photos("6")[:url], class: "kra-ph-box", "rc-box-phs".to_sym => production_photos("6")[:list], "rc-box-collection".to_sym => "production"  %></a>
            </div>
            <div class = "small-12 medium-4 columns tb-pad-s">
                    <a><%= image_tag production_photos("2")[:url], class: "kra-ph-box tb-pad-s", "rc-box-phs".to_sym => production_photos("2")[:list], "rc-box-collection".to_sym => "production"  %></a>
                    <p class = "stat text-center">
                         <%= Time.now.year.to_i - 2004 %> <%= t :years %>
                     </p>
                     <p class = "rc-param-name-b text-center">
                         <%= t :experience_of_shipbuilding %>
                     </p>
                     <p class = "text-center">
                         <%= link_to "#{t(:more).mb_chars.capitalize}...", about_path %>
                     </p>
            </div>
            <div class = "small-12 medium-4 columns">
                <p class = "stat text-center">
                     3,800 <%= t :m_short %><span class = "degree">2</span>
                 </p>
                 <p class = "rc-param-name-b text-center">
                     <%= t :production_and_warehouse_space %>
                 </p>
                 <a><%= image_tag production_photos("1")[:url], class: "kra-ph-box", "rc-box-phs".to_sym => production_photos("1")[:list], "rc-box-collection".to_sym => "production"  %></a>
            </div>    
        </div>
    </div>

</div>

app/views/realcraft_pages/please_wait.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:default_title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
      <div class = "row tb-pad-s">
          <div class = "small-12 small-centered columns">
              <%= image_tag "logo_vertical_colored.png", style: "height: 150px;", class: "float-center" %>
          </div>
          
      </div>
      <div class = "row tb-pad-s">
          <div class = "small-12 medium-offset-1 medium-5 columns">
              <div class="flex-video widescreen">
              <iframe width="496" height="279" src="https://www.youtube.com/embed/fxN92HTzx4U" frameborder="0" allowfullscreen></iframe>
              </div>
          </div>
          <div class = "small-12 medium-5 end columns">
              <div class="flex-video widescreen">
              <iframe width="496" height="279" src="https://www.youtube.com/embed/J0JQXQbo01M" frameborder="0" allowfullscreen></iframe>
              </div>
          </div>
      </div>
      <div class = "row">
          <div class = "small-11 small-centered columns text-center">
             <h4 class = "float-center"><%= t(:coming_soon) %>...</h4>
          </div>
      </div>
  </body>
</html>

app/views/realcraft_pages/prices.html.erb
<div class = "tb-pad-s">
    <div class = "row">
        <div class = "small-12 columns">
            <%= rc_header(t(:prices))  %>
        </div>
    </div>
</div>

<%= render "simple_pages_content", content: prices_page_content %>
<div id = "boat-request-form" style = 'display: none;'>
    <%= render "boat_request_form", is_boat_page: false %>
</div>

app/views/realcraft_pages/realcraft_190.html.erb
<%= render "boat_view_template" if !@boat.nil? %>

app/views/realcraft_pages/realcraft_200.html.erb
<%= render "boat_view_template" %>