config/routes.rb
Rails.application.routes.draw do

  get 'shop_pages/index'

  get 'shop_pages/boats'

  get 'shop_pages/shops'

  get 'photo/show'

  get 'photo/destroy'

  resources :property_types
  post "/copy_property_values", to: "property_types#copy_property_values" #для копирования значений свойств с одного типа лодки или продукта на другой
  
  #products
  resources :products
  get "/manage_products", to: "products#manage_index", as: :manage_products
  #product_types
  resources :product_types
  get "/manage_product_types", to: "product_types#manage_index", as: :manage_product_types
  #boat_type_modifications
  resources :boat_type_modifications, only: [:edit, :update]
  #user_requests
  resources :user_requests
  get "my_boats", to: "user_requests#my_requests", as: :my_boats #мои лодки 
  #shops
  resources :shops
  get "/manage_shops/:id", to: "shops#manage_show", as: :manage_shop                #страница управления магазином
  get "/manage_shops", to: "shops#manage_index", as: :manage_shops                  #управление магазинами
  get "/change_shop_status/:id", to: "shops#change_status", as: :change_shop_status #изменение статуса
  get "/manage_shops/:id/boats_for_sale", to: "shops#boats_for_sale", as: :manage_bfs_in_shop #управление лодками в магазине
  get "/manage_shops/:id/product_types/:product_type_id", to: "shops#manage_shop_products", as: :manage_shop_products #управление товарами магазине
  get "/shops/:id/product_types/:product_type_id", to: "shops#shop_products"
  resources :shop_products, only: [:update, :destroy, :create]
  get "/shops/:shop_id/products/:product_id", to: "shop_products#show", as: :in_shop_product
  
  #shop_products
  


  #end
  #locations
  get "/locations/regions/:country_id", to: "locations#regions"
  get "/locations/cities/:region_id", to: "locations#cities"
  get "/add_country", to: "locations#add_country"
  post "/add_country", to: "locations#add_country"
  #end
  #boat_for_sales
  resources :boat_for_sales
  post "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/parse_selected_options_file", to: "boat_for_sales#parse_selected_options_file"
  get "/manage_boat_for_sale", to: "boat_for_sales#manage_index", as: :manage_boat_for_sales
  get "/boat_for_sales/:id/switch_favorites", to: "boat_for_sales#switch_favorites"
  get "/favorites", to: "boat_for_sales#favorites"
  get "/boat_for_sales/:id/buy", to: "boat_for_sales#buy", as: :buy_bfs
  #end
  #boat_option_types
  resources :boat_option_types, only: [:index, :show, :update]
  #end
  #photos
  resources :photos, only: [:show, :destroy]
  post '/upload_photo/:entity/:entity_id', to: 'photos#upload'
  get "/entity_photos/:entity/:entity_id", to: 'photos#entity_photos'
  put "/entity_photos/:id", to: 'photos#update_entity_photo'
  delete "/entity_photos/:id", to: "photos#destroy_entity_photo" #удаляем ссылки на фотографию от boat_type или product (удаление фотографии)
  
  #end
  get "/test_page", to: "pages#test_page"
  get "/about", to: "pages#about", as: :about
  get "/boats/:id", to: "pages#boat", as: :tm_site_boat
  
  resources :boat_series, only: [:index, :create, :update, :destroy, :show]
  resources :trademarks, only: [:index, :create, :update, :destroy, :show]
  root to: 'pages#index'
  
  
  get "/check_user", to: "users#check", as: :check_user
  get "/cabinet", to: "sessions#current_user_page", as: :my
  get "/signin", to: "sessions#new", as: :signin
  post "/signin", to: "sessions#new"
  get "/signout", to: "sessions#destroy", as: :signout
  get "/signup", to: "users#new", as: :signup
  
  #get "/boat_types_import", to: "pages#boat_type_import"
  
  
  resources :sessions, only: [:new, :create]
  
  resources :boat_parameter_values, only: [:update]
  get "/boat_parameter_values/:id/:boat_type_id", to: "boat_parameter_values#switch_bind", as: :switch_bind_parameter_value #привязка-отвязка атрибутов от лодки
  resources :boat_parameter_types, only: [:new, :create, :destroy, :edit, :update, :index]
  post "/reorder_boat_parameter_types", to: "boat_parameter_types#update_numbers"
  
  resources :boat_types, only: [:create, :edit, :update, :destroy, :show]
  post '/boat_types/:id/add_configurator_entity', to: "boat_types#add_configurator_entity"  
  get "/manage_boat_types", to: "boat_types#manage_index", as: :manage_boat_types
  get '/boat_types/:id/photos', to: "boat_types#photos", as: :boat_type_photos
  get '/boat_types/:id/videos', to: 'boat_types#videos', as: :boat_type_videos
  get '/boat_types/:id/photos/:photo_id', to: "boat_types#photo", as: :boat_photo
  get '/boat_types/:id/property_values', to: 'boat_types#property_values'
  get '/boat_types/:id/modifications/:modification_id', to: 'boat_types#modification_show', as: :modification
  put '/boat_types/:id/property_values', to: 'boat_types#update_property_values'
  post '/boat_types/:id/modifications', to: 'boat_types#create_modification'
  get '/boat_types/:id/modifications', to: 'boat_types#modifications', as: :boat_type_modifications
  get '/get_boat_types_list', to: 'boat_types#get_boat_types_list'
  post "/copy_photos", to: "boat_types#copy_photos"
  get '/boat_types/:id/options', to: "boat_types#options", as: :boat_type_options
  resources :users
  
  resources :boat_property_types, only: [:index, :create] 
  
  #Realcraft Part--------------------------------------------------------------------------------------
  #get 'about', to: 'realcraft#about', as: :about
  #get "prices", to: "pages#prices", as: :prices
  get "dealers", to: "realcraft_pages#dealers", as: :realcraft_dealers
  get 'realcraft190', to: 'realcraft_pages#realcraft_190', as: :realcraft_190
  get 'realcraft200', to: 'realcraft_pages#realcraft_200', as: :realcraft_200
  get "wait", to: 'realcraft_pages#please_wait', as: :realcraft_wait
  get "about_realcraft", to: 'realcraft_pages#about', as: :realcraft_about
  post "send_boat_request", to: 'realcraft_pages#send_boat_request', as: :realcraft_send_boat_request
  post "send_dealer_request", to: 'realcraft_pages#send_dealer_request', as: :realcraft_send_dealer_request
  
  
  #videos Part
  resources :videos, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type
  has_many :entity_property_values, as: :entity, dependent: :delete_all
  has_many :shop_products, dependent: :delete_all
  has_many :entity_photos, as: :entity, dependent: :delete_all
  has_many :photos, through: :entity_photos
  
  accepts_nested_attributes_for :entity_property_values
  
  accepts_nested_attributes_for :photos
  def photos_attributes=(attrs)
    if !attrs.blank?
      self.photos.create(attrs)
      #attrs.each {|ph| self.photos.create(link: ph[:link], uploader_id: self.modifier_id)}
    end
  end
  
  def property_values
    self.entity_property_values.where(property_type_id: product_type.product_types_property_types.pluck(:property_type_id))
  end
  
  def prop_vals_for_shop(locale='ru')
    entity_property_values.includes(property_type: :product_types_property_types).order("product_types_property_types.order_number ASC").to_a.map do |epv| 
      prop_type_prod_type = epv.property_type.product_types_property_types.find_by(product_type_id: product_type_id, property_type: epv.property_type.id)
      {
      id: epv.property_type_id,
      name: epv.property_type["#{locale}_name".to_sym],
      short_name: epv.property_type["#{locale}_short_name".to_sym],
      measure: epv.property_type["#{locale}_measure".to_sym],
      value: epv.get_value,
      is_binded: epv.is_binded, 
      order_number: prop_type_prod_type.nil? ? 0 : prop_type_prod_type.order_number,
      more_than: prop_type_prod_type.nil? ? nil : prop_type_prod_type.more_than,
      less_than: prop_type_prod_type.nil? ? nil : prop_type_prod_type.less_than,
      equal: prop_type_prod_type.nil? ? nil : prop_type_prod_type.equal
     }
    end
  end
  
  def full_name
    %{#{manufacturer.blank? ? "" : "#{manufacturer} "}#{name}}
  end
  
  def entity_property_values_attributes=(attrs)
    return if attrs.blank?
    to_add = []
    attrs.values.each do |v|
      pv = self.entity_property_values.find_by(property_type_id: v[:property_type_id])
      if pv.nil?
        to_add.push v
      else
        pv.update_attributes(v)
      end
    end
    self.entity_property_values.create(to_add) if !to_add.blank?
  end
  
  def self.draft(p_type)
    d = find_by(is_draft: true, product_type_id: p_type.id)
    if d.nil?
      d = p_type.products.create(is_draft: true)
      d.update_attribute(:entity_property_values_attributes, p_type.default_property_values)
    end
    return d
  end

end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :product_types_property_types, dependent: :delete_all
  has_many :property_types, through: :product_types_property_types
  has_many :products, -> {where(is_draft: false)}, dependent: :destroy 
  before_save :set_plural_name
  accepts_nested_attributes_for :product_types_property_types
  
  def self.not_draft
    where(is_draft: false)#.order("name ASC")
  end
  
  def self.active
    where(is_active: true, is_draft: false)
  end
  
  def self.not_active
    where(is_active: false, is_draft: false)
  end
  def self.default_scope
    order("name ASC")
  end
  
 
  
  def self.draft
    #ProductType.new
    d = ProductType.where(is_draft: true).first
    d = ProductType.create(number_on_boat:1, is_draft: true) if d.nil?
    return d.reload
  end
  
  def product_types_property_types_attributes=(attrs)
    return if new_record? || attrs.nil?
    self.product_types_property_types.delete_all
    self.product_types_property_types.create(attrs.values) if !attrs.blank?
  end
  
  def properties_list #используется для отрисовки формы
      property_types.joins(:product_types_property_types).select(
              "property_types.id AS id, 
               property_types.ru_name AS ru_name,
               property_types.ru_measure AS ru_measure, 
               property_types.value_type AS value_type, 
               product_types_property_types.is_required AS is_required, 
               product_types_property_types.less_than AS less_than,
               product_types_property_types.more_than AS more_than,
               product_types_property_types.equal AS equal,
               product_types_property_types.order_number AS order_number").order("product_types_property_types.order_number ASC").distinct
  end
  
  def hash_view
    {
      id: self.id,
      name: self.name, 
      description: self.description,
      number_on_boat: self.number_on_boat,
      is_enable: self.is_enable,
      property_types: self.property_types
    }
  end
  
  def default_property_values
    return {} if self.property_types.blank?
    v = []
    self.property_types.each do |pt|
      v.push({property_type_id: pt.id, set_ru_value: pt.default_value, set_com_value: pt.default_value}) 
    end
    return v.to_ass_hash
  end

  private
  
  def set_plural_name
    self.plural_name = name if plural_name.blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_grants 
  before_action :set_product, only: [:edit, :destroy, :update, :photos, :show]
  def manage_index
    @title = @header = "Управление товарами"
  end
  
  def show
  end 
  
  def new
    @product_type = params[:product_type_id].blank? ? (ProductType.not_draft.first) : (ProductType.find_by(id: params[:product_type_id]))
    @title = @header = %{Добавление нового товара в категорию "#{@product_type.name}"}
    @product = Product.draft(@product_type)
  end
  
  def edit
    @title = @header = "Изменение товара"
  end
  
  def update
    p_params = product_params
    p_params[:is_draft] = false
    respond_to do |format|
      if @product.update_attributes(p_params) 
        format.html {redirect_to @product_type}
        format.json { render :show, status: :ok, location: @product }
      else
        @title = @header = "Добавление нового товара"
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.html {render :edit}
      end
    end
    
  end
  
  def destroy
    redirect_to @product.product_type if @product.destroy
  end
  
  private
  
  def check_grants
    redirect_to "/404" if !is_producer? and !is_admin? and !is_control?
  end
  
  def set_product
    @product = Product.find(params[:id])
    @product_type = @product.product_type
  end
  
  def product_params
    params.require(:product).permit(:name, :description, :manufacturer, entity_property_values_attributes:[:property_type_id, :is_binded, :set_ru_value, :set_com_value, :tag], photos_attributes:[:link, :uploader_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class = "row tb-pad-m">
    <div class = "small-12 columns">
        <ul class = 'bb-inline-menu' data-tabs id="bb-tabs" data-deep-link="false" data-turbolinks="false">
            <li class = 'tabs-title is-active'>
                <a href="#main">Информация</a>
            </li>
            <li class = 'tabs-title '>
               <a href="#photos">Фото</a>
            </li>
        </ul>
    </div>
</div>

<div class = "tabs-content" data-tabs-content="bb-tabs">
    <div class = 'tabs-panel is-active' id="main">
        <%= form_for(product) do |f| %>
            <div class = "row">
                <div class = "small-6 medium-3 columns">
                    <%= f.label :manufacturer, "Производитель" %>
                    <%= f.text_field :manufacturer %>
                </div>
                <div class = "small-12 medium-6 end columns">
                    <%= f.label :name, "Название" %>
                    <%= f.text_field :name %>
                </div>
            </div>
            <div class = "row">
                <div class = "small-12 columns">
                    <%= f.label :description, "Описание" %>
                    <%= f.text_area :description, rows: 7 %>
                </div>
            </div>
            <% if !product.property_values.blank? %>
                <div class = "row tb-pad-s">
                    <div class = "small-12 columns">
                        <%= render "property_types/property_values_table", form: f, property_values: product.property_values %>
                    </div>
                </div>
            <%end%>
            <div class = "row">
                <div class = "small-12 columns">
                    <%= f.submit "Сохранить", class: "button success" %>
                </div>
            </div>
        <%end%>
    </div>
    <div class = 'tabs-panel'  id="photos">
        <div class = "row tb-pad-s">
          <div class="small-12 columns">
              <%= form_for(product, html: {class: "dropzone"}) do |f| %>
                  <%= f.fields_for :photos_attributes do |ph| %>
                      <%= ph.hidden_field :uploader_id, value: current_user.id %>
                  <%end%>
              <%end%>
          </div>
        </div>
      <div id = "uploaded-photos-container" data-entity-id = "<%= product.id %>" data-entity-name = "product" class="row small-up-2 medium-up-3 tb-pad-s">
          
      </div>
      
    </div>
    
</div>

app/views/products/_manage_index_table.html.erb
<table>
    <thead>
        <tr>
            <th>
                Производитель
            </th>
            <th>
                Название
            </th>
            <th>
                Фотографий
            </th>
            <th>
                Добавлен в магазинах
            </th>
            <th colspan=3>
            </th>
        </tr>
    </thead>
    <tbody>
        <%if products.blank? %>
            <tr>
                <td colspan=7>
                    <p>
                        Нет ни одного товара в данной категории
                    </p>
                </td>
            </tr>
        <%else%>
            <% products.each do |product| %>
                <tr>
                    <td>
                        <%= product.manufacturer %>
                    </td>
                    <td>
                        <%= product.name %>
                    </td>
                    <td>
                        0<%#= product.photos.count %>
                    </td>
                    <td>
                        0<%#= product.product_shops.count %>
                    </td>
                    <td>
                        <%= link_to "<i class = 'fi-arrow-right'></i>".html_safe, product_path(product) %>
                    </td>
                    <td>
                        <%= link_to "<i class = 'fi-pencil'></i>".html_safe, edit_product_path(product), "data-turbolinks" => 'false' %>
                    </td>
                    <td>
                        <%= link_to "<i class = 'fi-trash'></i>".html_safe, product_path(product), method: "DELETE", confirm: "Вы уверены?" %>
                    </td>
                
                </tr>
            <% end %>
        <% end %>
    </tbody> 
</table>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/manage_index.html.erb
<div class = "row">
    <div class = "small-12 columns tb-pad-s">
        <%= link_to "Добавить ", new_product_type_path, class: "button" %>
    </div>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
#to_do